### ISSUE TITLE
register repository to be conform with REUSE standard

### ISSUE THREAD

**Issue by fxnitsch** [FEAT-ML/scengen#11]
# Request Summary
Once repository follows the [REUSE standards](https://reuse.software/spec/) which are checked with #10, it gets registered at the REUSE foundation to be formally attributed with this standard. Add the badge to the repository accordingly.

# Use case
Following the software developement standards defined by REUSE.

**Comment by fxnitsch** [comment]
> blocked: by https://github.com/FEAT-ML/scengen/milestone/2

not blocked anymore, since PyPI is not required for meeting REUSE standard

**Comment by dlr-cjs** [comment]
I would postpone this, as this repo is not the final one

**Comment by fxnitsch** [comment]
> I would postpone this, as this repo is not the final one

Agree
