### ISSUE TITLE
TypeTemplate: Rename section "Agents" to "Agent"

### ISSUE THREAD

**Issue by dlr-cjs** [FEAT-ML/scengen#58]
# Request Summary
If I understand correctly, one one agent can be dynamically created per template file. 
Thus, rename section "Agents" to "Agent" to make clear it can only be one...

**Comment by fxnitsch** [comment]
> # Request Summary
> 
> If I understand correctly, one one agent can be dynamically created per template file. Thus, rename section "Agents" to "Agent" to make clear it can only be one...

This is correct, will refactor as proposed
