### ISSUE TITLE
move repository to GitLab as AMIRIS-Scengen

### ISSUE THREAD

**Issue by fxnitsch** [FEAT-ML/scengen#72]
# Request Summary
As scengen is AMIRIS specific, we propose to move the project to GitLab where all other AMIRIS related code is hosted, specifically https://gitlab.com/dlr-ve/esy/amiris

Additionally, we propose to rename the project to "AMIRIS-Scengen" following the naming pattern of "AMIRIS-Py", "AMIRIS-Examples", etc.

# Use case
Harmonization of hosting AMIRIS code bases.

**Comment by dlr-cjs** [comment]
I agree to all three of your proposals
